In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Генерация идёт!!!

In [2]:
employees = pd.DataFrame()

In [3]:
employees['id'] = np.linspace(1, 100, num=100, dtype='int')

In [12]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      100 non-null    int32
dtypes: int32(1)
memory usage: 528.0 bytes

In [4]:
employees['name'] = np.random.choice(['Turbo', 'Artur', 'Turik', 'Sasha', 'Anya', 'Tanya', 'Danil', 'Artem', 'Bulat', 'Lexa'], size=100)

In [5]:
employees['department'] = np.random.choice(['IT', 'Audit', 'Sport', 'Business', 'Taxes', 'Banki', 'Technologies', 'Jurisdiction'], size=100)

In [6]:
employees['access_logs'] = np.random.choice(['low', 'medium', 'high', 'admin'], size=100)

In [7]:
employees.head()

   id   name    department access_logs
0   1  Turbo            IT         low
1   2  Turik         Sport        high
2   3   Anya         Taxes      medium
3   4  Turbo  Technologies         low
4   5  Danil  Technologies      medium

In [33]:
logs = pd.DataFrame()

In [34]:
logs['log_id'] = np.linspace(1, 1000, num=1000, dtype='int')

In [35]:
logs.shape

(1000, 1)

In [36]:
logs['user_id'] = np.random.randint(1, 100, size=1000)

In [37]:
import random
from datetime import datetime, timedelta

def generate_random_datetime(start_year, end_year):
    start = datetime(start_year, 1, 1, 00, 00, 00)
    end = start + timedelta(days=365 * (end_year - start_year + 1))
    random_delta = timedelta(days=random.randint(0, (end - start).days))
    return start + random_delta

print(generate_random_datetime(2025, 2026).date())

2025-05-01

In [39]:
logs['date'] = generate_random_datetime(2025, 2026).date()
logs['date'] = logs['date'].apply(lambda x: generate_random_datetime(2025, 2026).date())

In [40]:
logs.head()

   log_id  user_id        date
0       1       40  2026-08-25
1       2        4  2026-07-21
2       3        1  2025-02-04
3       4       36  2025-08-27
4       5       85  2026-11-07

In [73]:
def gen_ran_time():
    start = datetime(2025, 4, 1, 0, 0, 0)
    end = datetime(2025, 4, 1, 23, 59, 59)

    delta = end - start
    random_seconds = random.randint(0, int(delta.total_seconds()))

    return start + timedelta(seconds=random_seconds)

print(gen_ran_time().time())

22:57:42

In [74]:
logs['time'] = gen_ran_time().time()
logs['time'] = logs['time'].apply(lambda x: gen_ran_time().time())

In [75]:
logs.head()

   log_id  user_id        date      time
0       1       40  2026-08-25  06:48:41
1       2        4  2026-07-21  13:33:59
2       3        1  2025-02-04  13:40:15
3       4       36  2025-08-27  15:32:26
4       5       85  2026-11-07  15:38:58

In [76]:
logs['status'] = np.random.choice(['success', 'failure'], size=1000)

In [77]:
logs.head()

   log_id  user_id        date      time   status
0       1       40  2026-08-25  06:48:41  success
1       2        4  2026-07-21  13:33:59  success
2       3        1  2025-02-04  13:40:15  failure
3       4       36  2025-08-27  15:32:26  failure
4       5       85  2026-11-07  15:38:58  success

In [88]:
changes = pd.DataFrame()

In [89]:
changes['change_id'] = np.linspace(1, 200, num=200, dtype='int')

In [90]:
changes['user_id'] = np.random.randint(1, 100, size=200)

In [91]:
changes['changed_by'] = np.random.choice(['Turbo', 'Artur', 'Turik', 'Sasha', 'Anya', 'Tanya', 'Danil', 'Artem', 'Bulat', 'Lexa'], size=200)

In [92]:
changes['date'] = generate_random_datetime(2025, 2026).date()
changes['date'] = changes['date'].apply(lambda x: generate_random_datetime(2025, 2026).date())

In [93]:
changes['new_level'] = np.random.choice(['low', 'medium', 'high', 'admin'], size=200)

In [94]:
changes.head()

   change_id  user_id changed_by        date new_level
0          1       10      Danil  2026-12-20     admin
1          2       55      Danil  2026-11-24      high
2          3       86      Turbo  2025-04-03      high
3          4        7      Danil  2025-08-28    medium
4          5       40       Lexa  2026-05-12    medium